### ISSUE TITLE
column.php missing

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/wgfaker#11]
When I click to see the fields:

![image](https://user-images.githubusercontent.com/613686/211076042-4e53285d-5c65-48c9-9fbc-f1c47820a63d.png)

I'm being redirected to:

/admin/column.php?op=list&mid=289&tableid=10

but there is no  "/admin/column.php" file

**Comment by mambax7** [comment]
It seems like it should be "field.php" there, instead of "column.php"

**Comment by ggoffy** [comment]
hi
fixed with https://github.com/XoopsModules25x/wgfaker/pull/12

thank you
